substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "sdl-simulator"
  device_friendly_name: "SDL Simulator"

  # ------------------
  # ENTER API KEY HERE
  # ------------------
  api_key: "1YVnWKmTqIqoDgMNxjx+nU61w4hPRHY+H8RKvB+kghQ="

  # ----------------------------------------------------------------------------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # Is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)
  # ----------------------------------------------------------------------------------------------------
  total_pages: "3"

  # --------------
  # OTHER SETTINGS
  # --------------
  page_transition_time: 150ms # How long to animate the transition between pages.
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting

packages:
  HomeDicator: !include HomeDicator/device/sdl.yaml

sensor:
  # -----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # They need to be included here in order for the display to update values.
  # -----------------------------------------------------------------------

  - !include
      file: HomeDicator/core/templates/sensor_color.yaml
      vars:
        hass_sensor_id: "temp1"
        threshold_1: "10"
        threshold_2: "20"
        threshold_3: "30"
        color_1: "0x4169e1"   # blue  - below 10
        color_2: "0x2e8b57"   # green - 10 to 20
        color_3: "0xeebf41"   # yellow - 20 to 30
        color_4: "0xdc143c"   # red   - above 30

  - !include
      file: HomeDicator/core/templates/sensor_color.yaml
      vars:
        hass_sensor_id: "humidity1"
        threshold_1: "0"
        threshold_2: "40"
        threshold_3: "60"
        color_1: "0xdc143c"   # red   - below 0
        color_2: "0xeebf41"   # yellow - 0 to 40
        color_3: "0x2e8b57"   # green - 40 to 60
        color_4: "0x4169e1"   # blue  - above 60

  - !include
      file: HomeDicator/core/templates/sensor_color.yaml
      vars:
        hass_sensor_id: "co21"
        threshold_1: "400"
        threshold_2: "1000"
        threshold_3: "1500"
        color_1: "0x4169e1"   # blue  - below 400
        color_2: "0x2e8b57"   # green - 400 to 1000
        color_3: "0xeebf41"   # yellow - 1000 to 1500
        color_4: "0xdc143c"   # red   - above 1500

  - !include
      file: HomeDicator/core/templates/sensor_color.yaml
      vars:
        hass_sensor_id: "voc1"
        threshold_1: "80"
        threshold_2: "150"
        threshold_3: "200"
        color_1: "0x4169e1"   # blue  - below 80
        color_2: "0x2e8b57"   # green - 80 to 150
        color_3: "0xeebf41"   # yellow - 150 to 200
        color_4: "0xdc143c"   # red   - above 200

  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "temp2"

  - !include
      file: HomeDicator/core/templates/light_sensor.yaml
      vars:
        hass_light_id: "light1"
        color: "0xeebf41"
        icon: "\U000F0335"
        icon_off: "\U000F0336"

binary_sensor:
  # ---------------------
  # ADD YOUR SENSORS HERE
  # ---------------------


switch:
  # ----------------------
  # ADD YOUR SWITCHES HERE
  # ----------------------



lvgl:
  pages:
    # ----------------------------
    # ADD / ADJUST YOUR PAGES HERE
    # ----------------------------
    - id: first_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Device" # CHANGE PAGE TITLE HERE
        - obj:
            styles: content_container
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xdc143c
                    hass_sensor_id: "temp1"
                    unit: "°C"
                    icon: "\U000F050F"
                    title: "Temperature"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0x4169e1
                    hass_sensor_id: "humidity1"
                    unit: "%"
                    icon: "\U000F058E"
                    title: "Humidity"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "co21"
                    unit: "ppm"
                    icon: "\U000F07E4"
                    title: "CO²"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0x2e8b57
                    hass_sensor_id: "voc1"
                    unit: ""
                    icon: "\U000F0D43"
                    title: "Air Quality"
    - id: second_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Page 2" # CHANGE PAGE TITLE HERE
        - obj:
            styles: content_container
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "temp2"
                    icon: "\U000F0F55"
                    unit: "°C"
                    title: "Temp 2"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/light/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_light_id: "light1"
                    icon: "\U000F0335"
                    icon_off: "\U000F0336"
