platform: gpio
internal: true
id: indicator_button
name: "Indicator Button"
pin:
  number: GPIO38
  inverted: yes
  mode:
    input: true
    pullup: true
on_press:
  then:
    - if:
        condition: lvgl.is_paused
        then:
          - script.execute: activity_detected
        else:
          - logger.log: "Button pressed - turning screen off"
          - light.turn_off: indicator_display_backlight
          - delay: 200ms
          - lvgl.pause:
              show_snow: true
